version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:17.2.0
    working_directory: /home/circleci/lodgify
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm run install-all
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: /home/circleci/lodgify
          paths:
            - node_modules
      - persist_to_workspace:
          root: /home/circleci/lodgify
          paths:
            - server/node_modules

  linter-license-security-checks:
    docker:
      - image: cimg/node:17.2.0
    working_directory: /home/circleci/lodgify
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/lodgify
      - run:
          name: License checks
          command: npm run license-check
      - run:
          name: Lint commit
          command: npm run lint:commit

  test:
    docker:
      - image: cypress/browsers:node10.16.0-chrome77-ff71
    working_directory: /home/circleci/lodgify
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/lodgify
      - run:
          name: Install cypress
          command: npm install && npx cypress install
      - run:
          name: Run Integration Tests
          command: npm run cy:ci
      - store_artifacts:
          path: /home/circleci/lodgify/cypress/videos
      - store_artifacts:
          path: /home/circleci/lodgify/cypress/screenshots
      - store_test_results:
          path: /home/circleci/lodgify/test-results

  build-artifact:
    docker:
      - image: cimg/node:17.2.0
    working_directory: /home/circleci/lodgify
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/lodgify
      - run:
          name: Generate and Release version
          command: npm run semantic-release

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - linter-license-security-checks:
          requires:
            - install
      - test:
          requires:
            - install
      - build-artifact:
          filters:
            branches:
              only:
                - main
          context:
            - github
          requires:
            - test
